name: onspot_cleaner
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.0
  intl: ^0.19.0 
  flutter_svg: ^2.0.0 
  cached_network_image: ^3.2.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.0.2
  logger: ^2.4.0
  google_fonts: ^6.2.1  
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  flutter_riverpod: ^2.6.1
  device_info_plus: ^11.1.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/vacuum.png
    - assets/images/messy.png
    - assets/images/home.png
    - assets/images/home.svg
    - assets/images/plus.svg
    - assets/images/history.svg
    - assets/images/user.svg
    - assets/images/bell.svg
    - assets/images/calendar.svg
    - assets/images/bellring.svg
    - assets/images/ear.svg
    - assets/images/thumbs_up.svg
    - assets/images/search.svg
    - assets/images/mop.svg
    - assets/images/vacuuming.svg
    - assets/images/wipe.svg
    - assets/images/window.svg
    - assets/images/toilet.svg
    - assets/images/welcome_vacuum.png
    - assets/images/welcome.svg
    